BEGIN TRANSACTION;
DROP TABLE IF EXISTS "status";
CREATE TABLE IF NOT EXISTS "status" (
	"id"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT NOT NULL,
	"value"	TEXT,
	"type"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "sounds";
CREATE TABLE IF NOT EXISTS "sounds" (
	"id"	INTEGER NOT NULL UNIQUE,
	"text"	TEXT NOT NULL,
	"file_path"	TEXT NOT NULL,
	"proximity_volume_adjust"	REAL NOT NULL DEFAULT 1,
	"intensity"	REAL NOT NULL DEFAULT 0.5,
	"replay_wait"	INTEGER NOT NULL DEFAULT 0,
	"collections"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
INSERT INTO "status" VALUES (NULL,'light_level','0.5','f');
INSERT INTO "status" VALUES (NULL,'wakefulness','1.0','f');
INSERT INTO "status" VALUES (NULL,'horny','0.0','f');
INSERT INTO "status" VALUES (NULL,'sexual_arousal','0.0','f');
INSERT INTO "status" VALUES (NULL,'breath_intensity','0.00','f');
INSERT INTO "status" VALUES (NULL,'sleep_tilt_x','0.62','f');
INSERT INTO "status" VALUES (NULL,'sleep_tilt_y','3.15','f');
INSERT INTO "sounds" VALUES (NULL,'*yawns*','sounds/conversation/groans.wav',0.75,0.5,300,'sleepy');
INSERT INTO "sounds" VALUES (NULL,'Hmm hmm.','sounds/conversation/hmm_hm.wav',0.75,0.5,300,'sleepy');
INSERT INTO "sounds" VALUES (NULL,'Hmmm, baby.','sounds/conversation/hmmm_baby.wav',0.75,0.5,3600,'sleepy');
INSERT INTO "sounds" VALUES (NULL,'Mmm hmm.','sounds/conversation/mmm_hmm.wav',0.75,0.5,300,'sleepy');
INSERT INTO "sounds" VALUES (NULL,'*sleepy whimper*','sounds/conversation/sleepy_whimper_01.wav',0.75,0.5,300,'sleepy');
INSERT INTO "sounds" VALUES (NULL,'*sleepy whimper*','sounds/conversation/sleepy_whimper_02.wav',0.75,0.5,300,'sleepy');
INSERT INTO "sounds" VALUES (NULL,'*sleepy groan*','sounds/conversation/sleepy_woke_up_groan.wav',0.75,0.5,7200,'sleepy');
INSERT INTO "sounds" VALUES (NULL,'Uh hmm.','sounds/conversation/uh_hmm-2-2.wav',0.75,0.5,300,'sleepy');
INSERT INTO "sounds" VALUES (NULL,'Uh hmm.','sounds/conversation/uh_hmm-2.wav',0.75,0.5,300,'sleepy');
INSERT INTO "sounds" VALUES (NULL,'Uh hmm.','sounds/conversation/uh_hmm-3.wav',0.75,0.5,300,'sleepy');
INSERT INTO "sounds" VALUES (NULL,'Uh hmm.','sounds/conversation/uh_hmm-4.wav',0.75,0.5,300,'sleepy');
INSERT INTO "sounds" VALUES (NULL,'Uh hmm.','sounds/conversation/uh_hmm.wav',0.75,0.5,300,'sleepy');
INSERT INTO "sounds" VALUES (NULL,'Uh huh.','sounds/conversation/uh_huh-2.wav',0.75,0.5,300,'sleepy');
INSERT INTO "sounds" VALUES (NULL,'Uh huh.','sounds/conversation/uh_huh.wav',0.75,0.5,300,'sleepy');
INSERT INTO "sounds" VALUES (NULL,'*kiss*','sounds/kissing/kissing_01.wav',0.75,0.5,60,'kissing');
INSERT INTO "sounds" VALUES (NULL,'*kiss*','sounds/kissing/kissing_02.wav',0.75,0.5,60,'kissing');
INSERT INTO "sounds" VALUES (NULL,'*kiss*','sounds/kissing/kissing_03.wav',0.75,0.5,60,'kissing');
INSERT INTO "sounds" VALUES (NULL,'*kiss*','sounds/kissing/kissing_04.wav',0.75,0.5,60,'kissing');
INSERT INTO "sounds" VALUES (NULL,'*kiss*','sounds/kissing/kissing_05.wav',0.75,0.5,60,'kissing');
INSERT INTO "sounds" VALUES (NULL,'*kiss*','sounds/kissing/kissing_06.wav',0.75,0.5,60,'kissing');
INSERT INTO "sounds" VALUES (NULL,'*kiss*','sounds/kissing/kissing_07.wav',0.75,0.5,60,'kissing');
INSERT INTO "sounds" VALUES (NULL,'*kiss*','sounds/kissing/kissing_08.wav',0.75,0.5,60,'kissing');
INSERT INTO "sounds" VALUES (NULL,'*kiss*','sounds/kissing/kissing_09.wav',0.75,0.5,60,'kissing');
INSERT INTO "sounds" VALUES (NULL,'*kiss*','sounds/kissing/kissing_10.wav',0.75,0.5,60,'kissing');
INSERT INTO "sounds" VALUES (NULL,'*kiss*','sounds/kissing/kissing_11.wav',0.75,0.5,60,'kissing');
INSERT INTO "sounds" VALUES (NULL,'*laughs*','sounds/laughs/laugh_lessquiet_01.wav',0.75,0.5,60,'laughing');
INSERT INTO "sounds" VALUES (NULL,'*laughs*','sounds/laughs/laugh_lessquiet_02.wav',0.75,0.5,60,'laughing');
INSERT INTO "sounds" VALUES (NULL,'*laughs*','sounds/laughs/laugh_lessquiet_03.wav',0.75,0.5,60,'laughing');
INSERT INTO "sounds" VALUES (NULL,'*laughs*','sounds/laughs/laugh_quiet_01.wav',0.75,0.5,60,'laughing');
INSERT INTO "sounds" VALUES (NULL,'*laughs*','sounds/laughs/laugh_quiet_02.wav',0.75,0.5,60,'laughing');
INSERT INTO "sounds" VALUES (NULL,'*laughs*','sounds/laughs/laugh_quiet_03.wav',0.75,0.5,60,'laughing');
INSERT INTO "sounds" VALUES (NULL,'Hmm.','sounds/conversation/whimper_01.wav',0.75,0.5,60,'sleepy');
INSERT INTO "sounds" VALUES (NULL,'Hmm.','sounds/conversation/whimper_02.wav',0.75,0.5,60,'sleepy');
INSERT INTO "sounds" VALUES (NULL,'Hmm.','sounds/conversation/whimper_03.wav',0.75,0.5,60,'sleepy');
INSERT INTO "sounds" VALUES (NULL,'I couldn''t help it.','sounds/sex/i_couldnt_help_it.wav',1.0,0.1,7200,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'I love you inside me.','sounds/sex/i_love_you_inside_me.wav',1.0,0.4,7200,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'I want you to cum inside me!','sounds/sex/i_want_you_to_cum_inside_me.wav',1.0,0.9,7200,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'You can squeeze my tits.','sounds/sex/you_can_squeeze_my_tits.wav',1.0,0.3,1800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'You feel so big inside me.','sounds/sex/you_feel_so_big_inside_me.wav',1.0,0.6,1800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/001.wav',1.0,0.4,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/002.wav',1.0,0.7,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/003.wav',1.0,0.2,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/004.wav',1.0,0.2,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/005.wav',1.0,0.7,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/006.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/007.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/008.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/009.wav',1.0,0.6,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/010.wav',1.0,0.2,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/011.wav',1.0,0.1,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/012.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/013.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/014.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/015.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/016.wav',1.0,0.8,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/017.wav',1.0,0.3,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/018.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/019.wav',1.0,0.2,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/020.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/021.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/022.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/023.wav',1.0,0.7,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/024.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/025.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/026.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/027.wav',1.0,0.7,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/028.wav',1.0,0.7,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/029.wav',1.0,0.3,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/030.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/031.wav',1.0,0.2,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/032.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/033.wav',1.0,0.6,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/034.wav',1.0,0.6,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/035.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/036.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/037.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/038.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/039.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/040.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/041.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/042.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/043.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/044.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/045.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/046.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/047.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/048.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/049.wav',1.0,0.8,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/050.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/051.wav',1.0,0.7,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/052.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/053.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/054.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/055.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/056.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/057.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/058.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/059.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/060.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/061.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/062.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/063.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/064.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/065.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/066.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/067.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/068.wav',1.0,0.7,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/069.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/070.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/071.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/072.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/073.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/074.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/075.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/076.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/077.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/078.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/079.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/080.wav',1.0,0.8,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/081.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/082.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/083.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/084.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/085.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/086.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/087.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/088.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/089.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/090.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/091.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/092.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/093.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/094.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/095.wav',1.0,0.8,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/096.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/097.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/098.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/099.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/100.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/101.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/102.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/103.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/104.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/105.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/106.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/107.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/108.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/109.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/110.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/111.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/112.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/113.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/114.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/115.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/116.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/117.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/118.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/119.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/120.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/121.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/122.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/123.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/124.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/125.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/126.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/127.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/128.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/129.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/130.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/131.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/132.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/133.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/134.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/135.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/breathing/136.wav',1.0,0.5,0,'breathing');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/01.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/02.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/03.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/04.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/05.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/06.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/07.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/08.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/09.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/10.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/11.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/12.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/13.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/14.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/15.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/16.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/17.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/18.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/19.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/20.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/21.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/22.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/23.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/24.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/25.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/26.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/27.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/28.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/29.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/30.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/31.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/32.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/33.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/34.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/35.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/36.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/37.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/38.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/39.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/40.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/41.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/42.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/43.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/44.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/45.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/46.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/47.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/48.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/49.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/50.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/51.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/52.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/53.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/inhalation/54.wav',1.0,0.5,60,'inhalation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/001.wav',1.0,0.1,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/002.wav',1.0,0.1,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/003.wav',1.0,0.2,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/004.wav',1.0,0.2,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/005.wav',1.0,0.1,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/006.wav',1.0,0.2,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/007.wav',1.0,0.1,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/008.wav',1.0,0.2,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/009.wav',1.0,0.1,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/010.wav',1.0,0.1,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/011.wav',1.0,0.2,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/012.wav',1.0,0.1,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/013.wav',1.0,0.2,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/014.wav',1.0,0.2,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/015.wav',1.0,0.1,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/016.wav',1.0,0.1,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/017.wav',1.0,0.2,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/018.wav',1.0,0.5,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/019.wav',1.0,0.4,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/020.wav',1.0,0.4,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/021.wav',1.0,0.2,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/022.wav',1.0,0.1,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/023.wav',1.0,0.4,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/024.wav',1.0,0.5,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/025.wav',1.0,0.4,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/026.wav',1.0,0.4,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/027.wav',1.0,0.4,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/028.wav',1.0,0.5,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/029.wav',1.0,0.4,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/030.wav',1.0,0.5,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/031.wav',1.0,0.4,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/032.wav',1.0,0.5,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/033.wav',1.0,0.5,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/034.wav',1.0,0.8,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/035.wav',1.0,0.8,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/036.wav',1.0,0.9,3,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/037.wav',1.0,0.9,3,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/038.wav',1.0,0.9,3,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/039.wav',1.0,0.8,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/040.wav',1.0,0.2,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/041.wav',1.0,0.2,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/042.wav',1.0,0.3,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/043.wav',1.0,0.2,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/044.wav',1.0,0.4,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/045.wav',1.0,0.9,3,'sex_conversation,sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/046.wav',1.0,0.9,3,'sex_conversation,sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/047.wav',1.0,0.9,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/048.wav',1.0,0.8,3,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/049.wav',1.0,0.9,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/050.wav',1.0,0.9,3,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/051.wav',1.0,0.3,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/052.wav',1.0,0.2,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/053.wav',1.0,0.2,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/054.wav',1.0,0.2,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/055.wav',1.0,0.2,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'','sounds/sex_gen/056.wav',1.0,0.3,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'*augh*','sounds/conversation/augh_disgust.wav',0.75,0.5,60,'disgust');
INSERT INTO "sounds" VALUES (NULL,'*laughs*','sounds/laughs/laugh.wav',0.75,0.5,60,'laughing');
INSERT INTO "sounds" VALUES (NULL,'*laughs*','sounds/laughs/laughy_sound.wav',0.75,0.5,60,'laughing');
INSERT INTO "sounds" VALUES (NULL,'*sigh*','sounds/conversation/sigh_disgust.wav',0.75,0.5,60,'disgust');
INSERT INTO "sounds" VALUES (NULL,'*kiss*','sounds/kissing/kissing_12.wav',1.0,0.5,60,'kissing');
INSERT INTO "sounds" VALUES (NULL,'*kiss*','sounds/kissing/kissing_13.wav',1.0,0.5,60,'kissing');
INSERT INTO "sounds" VALUES (NULL,'*kiss*','sounds/kissing/kissing_14.wav',1.0,0.5,60,'kissing');
INSERT INTO "sounds" VALUES (NULL,'*kiss*','sounds/kissing/kissing_15.wav',1.0,0.5,60,'kissing');
INSERT INTO "sounds" VALUES (NULL,'*kiss*','sounds/kissing/kissing_16.wav',1.0,0.5,60,'kissing');
INSERT INTO "sounds" VALUES (NULL,'*laughs*','sounds/laughs/laugh_01.wav',0.75,0.5,60,'laughing');
INSERT INTO "sounds" VALUES (NULL,'*laughs*','sounds/laughs/laugh_02-2.wav',0.75,0.5,60,'laughing');
INSERT INTO "sounds" VALUES (NULL,'*laughs*','sounds/laughs/laugh_02.wav',0.75,0.5,60,'laughing');
INSERT INTO "sounds" VALUES (NULL,'*laughs*','sounds/laughs/laugh_03.wav',0.75,0.5,60,'laughing');
INSERT INTO "sounds" VALUES (NULL,'*laughs*','sounds/laughs/laugh_quiet_04.wav',0.75,0.5,60,'laughing');
INSERT INTO "sounds" VALUES (NULL,'*laughs*','sounds/laughs/laugh_04.wav',0.75,0.5,60,'laughing');
INSERT INTO "sounds" VALUES (NULL,'*kiss*','sounds/kissing/kissing_17.wav',1.0,0.5,60,'kissing');
INSERT INTO "sounds" VALUES (NULL,'*kiss*','sounds/kissing/kissing_18.wav',1.0,0.5,60,'kissing');
INSERT INTO "sounds" VALUES (NULL,'*kiss*','sounds/kissing/kissing_19.wav',1.0,0.5,60,'kissing');
INSERT INTO "sounds" VALUES (NULL,'*laughs*','sounds/laughs/laugh_5.wav',0.75,0.5,60,'laughing');
INSERT INTO "sounds" VALUES (NULL,'*laughs*','sounds/laughs/laugh_6.wav',0.75,0.5,60,'laughing');
INSERT INTO "sounds" VALUES (NULL,'*laughs*','sounds/laughs/laugh_7.wav',0.75,0.5,60,'laughing');
INSERT INTO "sounds" VALUES (NULL,'*laughs*','sounds/laughs/laugh_8.wav',0.75,0.5,60,'laughing');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/conversation/mmm.wav',0.75,0.5,60,'sleepy');
INSERT INTO "sounds" VALUES (NULL,'Hmmm.','sounds/conversation/hmmm_2.wav',0.75,0.5,60,'sleepy');
INSERT INTO "sounds" VALUES (NULL,'Hmmm.','sounds/conversation/hmmm.wav',0.75,0.5,60,'sleepy');
INSERT INTO "sounds" VALUES (NULL,'*laughs*','sounds/laughs/laugh_09.wav',0.75,0.5,1800,'laughing');
INSERT INTO "sounds" VALUES (NULL,'*laughs*','sounds/laughs/laugh_10.wav',0.75,0.5,1800,'laughing');
INSERT INTO "sounds" VALUES (NULL,'Mm hmm.','sounds/conversation/mm_hmm.wav',0.75,0.5,60,'sleepy');
INSERT INTO "sounds" VALUES (NULL,'*laughs*','sounds/sleepysweet/laugh.wav',0.75,0.5,60,'laughing');
INSERT INTO "sounds" VALUES (NULL,'*sleepy groan*','sounds/sleepysweet/sleepy_groan.wav',0.75,0.5,60,'sleepy');
INSERT INTO "sounds" VALUES (NULL,'*yawns*','sounds/sleepysweet/yawn.wav',0.75,0.5,7200,'sleepy');
INSERT INTO "sounds" VALUES (NULL,'Do you like it?','sounds/sexy1/do_you_like_it.wav',1.0,0.1,1800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Fuck I''m gonna cum!','sounds/sexy1/fuck_im_gonna_cum.wav',1.0,0.9,30,'sex_near_O');
INSERT INTO "sounds" VALUES (NULL,'Fuck! Kiss me!','sounds/sexy1/fuck_kiss_me.wav',1.0,0.5,1800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Fuck me!','sounds/sexy1/fuck_me2.wav',1.0,0.4,300,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Fuck me!','sounds/sexy1/fuck_me3.wav',1.0,0.5,60,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Fuck me, please.','sounds/sexy1/fuck_me_please.wav',1.0,0.3,1800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Fuck me, right now!','sounds/sexy1/fuck_me_right_now.wav',1.0,0.4,1800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Fuck me!','sounds/sexy1/fuck_me.wav',1.0,0.5,1800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Fuck, you''re amazing.','sounds/sexy1/fuck_youre_amazing.wav',1.0,0.1,3600,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'God!','sounds/sexy1/god_1.wav',1.0,0.6,1800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Holy fuck!','sounds/sexy1/holy_fuck_1.wav',1.0,0.7,3600,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'I love that.','sounds/sexy1/i_love_that.wav',0.75,0.1,1800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'I love you.','sounds/sexy1/i_love_you2.wav',0.75,0.0,18000,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'I love you.','sounds/sexy1/i_love_you3.wav',0.75,0.0,7200,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'I love you.','sounds/sexy1/i_love_you.wav',0.75,0.0,7200,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'I''m gonna cum!','sounds/sexy1/im_gonna_cum.wav',1.0,0.9,60,'sex_near_O');
INSERT INTO "sounds" VALUES (NULL,'I''m so wet for you.','sounds/sexy1/im_so_wet_for_you.wav',1.0,0.3,1800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'I''m so wet.','sounds/sexy1/im_so_wet.wav',1.0,0.3,3600,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'I want to cum for you! Kiss me!','sounds/sexy1/i_want_to_cum_for_you_kiss_me.wav',1.0,1.0,1800,'sex_near_O');
INSERT INTO "sounds" VALUES (NULL,'I want to cum for you so bad! Kiss_me!','sounds/sexy1/i_want_to_cum_for_you_so_bad_kiss_me.wav',1.0,1.0,1800,'sex_near_O');
INSERT INTO "sounds" VALUES (NULL,'I want to cum for you so_bad!','sounds/sexy1/i_want_to_cum_for_you_so_bad.wav',1.0,1.0,3600,'sex_near_O');
INSERT INTO "sounds" VALUES (NULL,'I want to cum for you!','sounds/sexy1/i_want_to_cum_for_you.wav',1.0,1.0,3600,'sex_near_O');
INSERT INTO "sounds" VALUES (NULL,'I want you!','sounds/sexy1/i_want_you.wav',1.0,0.1,172800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Just, fuck me!','sounds/sexy1/just_fuck_me.wav',1.0,0.6,30,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'*draws a breath*','sounds/sexy1/drawbreath2.wav',1.0,0.7,7200,'sex');
INSERT INTO "sounds" VALUES (NULL,'*draws a breath*','sounds/sexy1/drawbreath.wav',1.0,0.7,7200,'sex');
INSERT INTO "sounds" VALUES (NULL,'Kiss me! Fuck me!','sounds/sexy1/kiss_me_fuck_me.wav',1.0,0.7,7200,'sex');
INSERT INTO "sounds" VALUES (NULL,'Kiss me!','sounds/sexy1/kiss_me.wav',1.0,1.0,1800,'sex');
INSERT INTO "sounds" VALUES (NULL,'*laughs*','sounds/sexy1/laugh.wav',0.85,0.0,300,'sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm10.wav',1.0,0.2,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm11.wav',1.0,0.2,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm12.wav',1.0,0.2,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm13.wav',1.0,0.1,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm14.wav',1.0,0.4,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm15.wav',1.0,0.2,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm16.wav',1.0,0.4,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm17.wav',1.0,0.5,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm18.wav',1.0,0.6,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm19.wav',1.0,0.7,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm20.wav',1.0,0.7,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm21.wav',1.0,0.7,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm22.wav',1.0,0.7,3,'sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm23.wav',1.0,0.9,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm24.wav',1.0,0.9,3,'sex_climax,sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm25.wav',1.0,0.9,5,'sex_climax,sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm26_1.wav',1.0,0.9,5,'sex_climax,sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm27_1.wav',1.0,0.9,5,'sex_climax,sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm28_1.wav',1.0,0.9,5,'sex_climax,sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm29_1.wav',1.0,0.8,0,'sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm2.wav',1.0,0.2,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm30_1.wav',1.0,0.8,0,'sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm31_1.wav',1.0,0.6,0,'sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm3.wav',1.0,0.4,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm4.wav',1.0,0.5,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm5.wav',1.0,0.3,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm6.wav',1.0,0.4,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm7.wav',1.0,0.2,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm8.wav',1.0,0.2,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm9.wav',1.0,0.3,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Mmm. Fuck yes!','sounds/sexy1/mmm_fuck_yes.wav',1.0,0.3,300,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Mmm. Please.','sounds/sexy1/mmm_please.wav',1.0,0.2,1800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sexy1/mmm.wav',1.0,0.3,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Oh, fuck yes!','sounds/sexy1/oh_fuck_yes.wav',1.0,0.5,1800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Oh, fuck! You''re making me shiver!','sounds/sexy1/oh_fuck_youre_making_me_shiver.wav',1.0,0.5,3600,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Oh, god!','sounds/sexy1/oh_god2.wav',1.0,0.6,60,'sex_conversation,sex_climax');
INSERT INTO "sounds" VALUES (NULL,'Oh, god! Fuck me!','sounds/sexy1/oh_god_fuck_me2.wav',1.0,0.6,1800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Oh, god! Fuck me!','sounds/sexy1/oh_god_fuck_me3.wav',1.0,0.6,3600,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Oh, god! Fuck me, right now!','sounds/sexy1/oh_god_fuck_me_right_now.wav',1.0,0.3,3600,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Oh, god! Fuck me!','sounds/sexy1/oh_god_fuck_me.wav',1.0,0.6,3600,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Oh, god! Fuck, mmm.','sounds/sexy1/oh_god_fuck_mmm.wav',1.0,0.7,3600,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Oh, god! Fuck!','sounds/sexy1/oh_god_fuck.wav',1.0,0.4,1800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Oh, god! I''m gonna cum!','sounds/sexy1/oh_god_im_gonna_cum.wav',1.0,1.0,3600,'sex_near_O');
INSERT INTO "sounds" VALUES (NULL,'Oh, god! I''m so close!','sounds/sexy1/oh_god_im_so_close.wav',1.0,1.0,1800,'sex_near_O');
INSERT INTO "sounds" VALUES (NULL,'Oh, god.','sounds/sexy1/oh_god.wav',1.0,0.4,28800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Oh, god, you''re so good at that.','sounds/sexy1/oh_god_youre_so_good_at_that.wav',1.0,0.1,172800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Please fuck me.','sounds/sexy1/please_fuck_me.wav',1.0,0.1,28800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Please, oh oh!','sounds/sexy1/please_oh_oh.wav',1.0,0.8,3600,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Please, will you please fuck me?','sounds/sexy1/please_will_you_please_fuck_me.wav',0.75,0.0,172800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'So wet.','sounds/sexy1/so_wet.wav',1.0,0.2,7200,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'That''s good.','sounds/sexy1/thats_good.wav',1.0,0.0,86400,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'What the fuck?!','sounds/sexy1/what_the_fuck.wav',0.9,0.5,172800,'disgust');
INSERT INTO "sounds" VALUES (NULL,'*sexy whimper*','sounds/sexy1/whimper.wav',1.0,0.1,300,'sex');
INSERT INTO "sounds" VALUES (NULL,'You asshole!','sounds/sexy1/you_asshole.wav',1.0,0.5,172800,'disgust');
INSERT INTO "sounds" VALUES (NULL,'You really like that.','sounds/sexy1/you_really_like_that2.wav',1.0,0.0,18000,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'You really like that.','sounds/sexy1/you_really_like_that.wav',1.0,0.0,7200,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'You''re amazing.','sounds/sexy1/youre_amazing.wav',0.75,0.2,28800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'You''re gonna cum already?','sounds/sexy1/youre_gonna_cum_already.wav',1.0,0.3,18000,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'You''re gonna cum for me.','sounds/sexy1/youre_gonna_cum_for_me2.wav',1.0,0.3,28800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'You''re gonna cum for me.','sounds/sexy1/youre_gonna_cum_for_me.wav',1.0,0.4,18000,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Oh fuck!','sounds/sex_climax/climax_01_ohfuck.wav',1.0,1.0,300,'sex_climax');
INSERT INTO "sounds" VALUES (NULL,'Oh oh!','sounds/sex_climax/climax_02_ohoh.wav',1.0,1.0,5,'sex_climax');
INSERT INTO "sounds" VALUES (NULL,'Oh fuck!','sounds/sex_climax/climax_03_ohfuck.wav',1.0,1.0,30,'sex_climax');
INSERT INTO "sounds" VALUES (NULL,'I think I''m gonna cum!','sounds/sex_climax/climax_04_i_think_im_gonna_cum.wav',1.0,1.0,3600,'sex_climax,sex_near_O');
INSERT INTO "sounds" VALUES (NULL,'Mm mmmm.','sounds/sex_climax/climax_05_mm_mm.wav',1.0,1.0,5,'sex_climax');
INSERT INTO "sounds" VALUES (NULL,'Mmm.','sounds/sex_climax/climax_06_mm.wav',1.0,1.0,5,'sex_climax');
INSERT INTO "sounds" VALUES (NULL,'Yes, baby!','sounds/sex_climax/climax_07_yes_baby.wav',1.0,1.0,3600,'sex_climax');
INSERT INTO "sounds" VALUES (NULL,'Oh! Oh!','sounds/sex_climax/climax_08_ohoh.wav',1.0,1.0,5,'sex_climax');
INSERT INTO "sounds" VALUES (NULL,'Oh!','sounds/sex_climax/climax_09_oh.wav',1.0,1.0,5,'sex_climax');
INSERT INTO "sounds" VALUES (NULL,'Cum inside me!','sounds/sex_climax/climax_10_cum_inside_me.wav',1.0,1.0,7200,'sex_climax');
INSERT INTO "sounds" VALUES (NULL,'Ohh, ah!','sounds/sex_climax/climax_11_ohah.wav',1.0,1.0,5,'sex_climax');
INSERT INTO "sounds" VALUES (NULL,'Ohh, ah!','sounds/sex_climax/climax_12_ohah.wav',1.0,1.0,5,'sex_climax');
INSERT INTO "sounds" VALUES (NULL,'Oh!','sounds/sex_climax/climax_13_oh.wav',1.0,1.0,5,'sex_climax');
INSERT INTO "sounds" VALUES (NULL,'Agh!','sounds/sex_climax/climax_14_ah.wav',1.0,1.0,5,'sex_climax');
INSERT INTO "sounds" VALUES (NULL,'Oh! Augh!','sounds/sex_climax/climax_15_ohah.wav',1.0,1.0,5,'sex_climax');
INSERT INTO "sounds" VALUES (NULL,'Oh! Augh!','sounds/sex_climax/climax_16_ohah.wav',1.0,1.0,5,'sex_climax');
INSERT INTO "sounds" VALUES (NULL,'Oh! Augh!','sounds/sex_climax/climax_17_ohah.wav',1.0,1.0,5,'sex_climax');
INSERT INTO "sounds" VALUES (NULL,'Don''t you dare stop!','sounds/sexy2/dont_you_dare_stop.wav',1.0,0.5,172800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'*laughs*','sounds/sexy2/laugh.wav',0.75,0.5,3600,'laughing');
INSERT INTO "sounds" VALUES (NULL,'Mm hmm.','sounds/sexy2/mm_hmm.wav',0.75,0.5,1800,'sleepy');
INSERT INTO "sounds" VALUES (NULL,'No, don''t you dare stop!','sounds/sexy2/no_dont_you_dare_stop.wav',1.0,0.7,172800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh10.wav',1.0,0.6,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh11.wav',1.0,0.3,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh12.wav',1.0,0.5,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh13.wav',1.0,0.3,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh14.wav',1.0,0.3,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh15.wav',1.0,0.6,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh16.wav',1.0,0.6,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh17.wav',1.0,0.6,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh18.wav',1.0,0.6,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh19.wav',1.0,0.5,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh! Ok.','sounds/sexy2/sex_augh20_ok.wav',1.0,0.3,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh21.wav',1.0,0.4,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh22.wav',1.0,0.7,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh23.wav',1.0,0.6,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh24.wav',1.0,0.7,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh25.wav',1.0,0.6,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh, yes!','sounds/sexy2/sex_augh26_yes.wav',1.0,0.7,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh! Keep going!','sounds/sexy2/sex_augh27_keepgoing.wav',1.0,0.6,172800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Augh! Don''t! Don''t stop!','sounds/sexy2/sex_augh28_dontdontstop.wav',1.0,0.5,172800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Augh! Don''t stop!','sounds/sexy2/sex_augh28_dontstop.wav',1.0,0.7,172800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh29.wav',1.0,0.6,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh2.wav',1.0,0.7,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh30.wav',1.0,0.5,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh31.wav',1.0,0.6,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh32.wav',1.0,0.4,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh! I love you!','sounds/sexy2/sex_augh33_iloveyou.wav',1.0,0.4,7200,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh34.wav',1.0,0.5,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh35.wav',1.0,0.6,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh36.wav',1.0,0.6,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh37.wav',1.0,0.4,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh! Oh yeah!','sounds/sexy2/sex_augh38_ohyeah.wav',1.0,0.6,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh! Yes! Keep going!','sounds/sexy2/sex_augh39_yeskeepgoing.wav',1.0,0.7,172800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Augh! Yes! Yes, keep going!','sounds/sexy2/sex_augh39_yesyeskeepgoing.wav',1.0,0.6,172800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh3.wav',1.0,0.6,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh40.wav',1.0,0.5,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh41.wav',1.0,0.6,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh42.wav',1.0,0.6,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh43.wav',1.0,0.6,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh44.wav',1.0,0.6,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh45.wav',1.0,0.7,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh46.wav',1.0,0.7,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh47.wav',1.0,0.7,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh48.wav',1.0,0.7,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh49.wav',1.0,0.7,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh! Ok.','sounds/sexy2/sex_augh4_ok.wav',1.0,0.2,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh50.wav',1.0,0.7,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh51.wav',1.0,0.7,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh52.wav',1.0,0.8,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh! Yes!','sounds/sexy2/sex_augh53_yes.wav',1.0,0.8,300,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh! Oh, yes!','sounds/sexy2/sex_augh54_ohyes.wav',1.0,0.8,300,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh! Keep going!','sounds/sexy2/sex_augh55_keepgoing.wav',1.0,0.8,172800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh56.wav',1.0,0.8,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh57.wav',1.0,0.6,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh! You''re getting close?','sounds/sexy2/sex_augh58_youregettingclose_1.wav',1.0,0.9,7200,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh5.wav',1.0,0.2,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh62.wav',1.0,0.7,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh! Please.','sounds/sexy2/sex_augh63_please.wav',1.0,0.6,300,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh64.wav',1.0,0.6,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh! Cum inside me!','sounds/sexy2/sex_augh65_cuminsideme_1.wav',1.0,1.0,172800,'sex_climax');
INSERT INTO "sounds" VALUES (NULL,'Augh! Cum inside me!','sounds/sexy2/sex_augh66_cuminsideme_2.wav',1.0,1.0,86400,'sex_climax');
INSERT INTO "sounds" VALUES (NULL,'Augh! Cum inside me!','sounds/sexy2/sex_augh67_cuminsideme_3.wav',1.0,1.0,7200,'sex_climax');
INSERT INTO "sounds" VALUES (NULL,'Augh! Yes!','sounds/sexy2/sex_augh68_yes.wav',1.0,0.7,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh69.wav',1.0,0.8,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh6.wav',1.0,0.5,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh70.wav',1.0,0.9,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh71.wav',1.0,0.9,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh! I''m gonna cum!','sounds/sexy2/sex_augh72_imgonnacum.wav',1.0,0.9,300,'sex_near_O');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh73.wav',1.0,0.9,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh74.wav',1.0,0.9,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh75.wav',1.0,0.9,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh76.wav',1.0,0.9,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh77.wav',1.0,0.9,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh78.wav',1.0,0.9,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh79.wav',1.0,0.9,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh80.wav',1.0,0.8,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh81.wav',1.0,0.7,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh82.wav',1.0,0.6,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh83.wav',1.0,0.6,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh! Oh, fuck!','sounds/sexy2/sex_augh8_ohfuck.wav',1.0,0.7,1800,'sex');
INSERT INTO "sounds" VALUES (NULL,'Augh!','sounds/sexy2/sex_augh9.wav',1.0,0.5,5,'sex');
INSERT INTO "sounds" VALUES (NULL,'Yes!','sounds/sexy2/sex_yes.wav',1.0,0.5,1800,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'*laughs*','sounds/kittensexy/laugh.wav',0.75,0.5,43200,'laughing');
INSERT INTO "sounds" VALUES (NULL,'Mm hmm.','sounds/kittensexy/mm_hmm_1.wav',0.75,0.5,3600,'sleepy');
INSERT INTO "sounds" VALUES (NULL,'Mm hmm.','sounds/kittensexy/mm_hmm_2.wav',0.75,0.5,3600,'sleepy');
INSERT INTO "sounds" VALUES (NULL,'I wanna feel your cock inside me.','sounds/sexconvo/i_wanna_feel_your_cock_inside_me_2.wav',1.0,0.0,345600,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'I wanna feel your cock inside me.','sounds/sexconvo/i_wanna_feel_your_cock_inside_me.wav',1.0,0.0,345600,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'I wanna feel your cock inside my pussy.','sounds/sexconvo/i_wanna_feel_your_cock_inside_my_pussy.wav',1.0,0.0,345600,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Oh, baby.','sounds/sexconvo/oh_baby.wav',1.0,0.0,43200,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Oh, I can feel your cock.','sounds/sexconvo/oh_i_can_feel_your_cock_2.wav',1.0,0.2,345600,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Oh, I can feel your cock.','sounds/sexconvo/oh_i_can_feel_your_cock_3.wav',1.0,0.2,345600,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Oh, I can feel your cock.','sounds/sexconvo/oh_i_can_feel_your_cock.wav',1.0,0.2,345600,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Oh, I can feel you.','sounds/sexconvo/oh_i_can_feel_you.wav',1.0,0.1,345600,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'Oh, I really like that.','sounds/sexconvo/oh_i_really_like_that.wav',1.0,0.0,86400,'sex_conversation');
INSERT INTO "sounds" VALUES (NULL,'','sounds/beep.wav',1.0,0.0,0,'beep');
INSERT INTO "sounds" VALUES (NULL,'','sounds/brain_onn_liine.wav',1.0,0.0,0,'brain_online');
INSERT INTO "sounds" VALUES (NULL,'','sounds/broca_failure.wav',1.0,0.0,0,'broca_failure');
INSERT INTO "sounds" VALUES (NULL,'','sounds/broca_is_connected.wav',1.0,0.0,0,'broca_connected');
INSERT INTO "sounds" VALUES (NULL,'','sounds/gye_roe_failure.wav',1.0,0.0,0,'gyro_failure');
INSERT INTO "sounds" VALUES (NULL,'','sounds/vagina_failure.wav',1.0,0.0,0,'vagina_failure');
INSERT INTO "sounds" VALUES (NULL,'','sounds/zearr_nicky_failure.wav',1.0,0.0,0,'wernicke_failure');
INSERT INTO "sounds" VALUES (NULL,'','sounds/zearr_nicky_is_connected.wav',1.0,0.0,0,'wernicke_connected');
INSERT INTO "sounds" VALUES (NULL,'','sounds/par_eye_et_all_lobe_failure.wav',1.0,0.0,0,'parietal_lobe_failure');
INSERT INTO "sounds" VALUES (NULL,'','sounds/par_eye_et_all_lobe_is_connected.wav',1.0,0.0,0,'parietal_lobe_connected');
COMMIT;
